# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

setCities = {'omerga', 'jalpaiguri', 'bhusawal', 'hyderabad', 'malegaon', 'amravati', 'other', 'tirupathi', 'rajkot', 'nashik', 'guntur', 'ongole', 'howrah', 'mumbai', 'amgaon', 'mohali', 'darjeeling', 'kolhapur', 'pusad', 'bhandara', 'korba', 'khamgaon', 'bangalore', 'bhiwandi', 'jabalpur', 'kedgaon', 'kalamb', 'ahmednagar', 'buldhana', 'kanpur', 'ghaziabad', 'sangamner', 'yavatmal', 'dhule', 'chennai', 'ahmedabad', 'udgir', 'mysore', 'thane', 'wardha', 'shirur', 'vashi', 'ranchi', 'beed', 'aurangabad', 'nagpur', 'latur', 'mangalore', 'indore', 'miraj', 'raipur', 'sangli', 'chandigarh', 'akluj', 'kamptee', 'washim', 'bareilly', 'jalgaon', 'patna', 'manchar', 'vijayawada', 'hooghly', 'chandrapur', 'siliguri', 'solapur', 'pimpri', 'kalyan', 'pune', 'puttaparthi', 'jalna', 'bhilai', 'durg', 'satara', 'bhopal', 'jaipur', 'nandurbar', 'ratnagiri', 'barshi', 'gurgaon', 'panvel', 'bhubaneshwar', 'parbhani', 'wai', 'new delhi', 'kolkata', 'noida', 'sinner', 'navi mumbai', 'faridabad', 'bilaspur', 'lucknow', 'akola', 'vadodara', 'aurangpura', 'agra', 'nanded', 'vishakapatnam', 'mangalagiri'}


# regex = r"(omerga|jalpaiguri|bhusawal|hyderabad|malegaon|amravati|other|tirupathi|rajkot|nashik|guntur|ongole|howrah|mumbai|amgaon|mohali|darjeeling|kolhapur|pusad|bhandara|korba|khamgaon|bangalore|bhiwandi|jabalpur|kedgaon|kalamb|ahmednagar|buldhana|kanpur|ghaziabad|sangamner|yavatmal|dhule|chennai|ahmedabad|udgir|mysore|thane|wardha|shirur|vashi|ranchi|beed|aurangabad|nagpur|latur|mangalore|indore|miraj|raipur|sangli|chandigarh|akluj|kamptee|washim|bareilly|jalgaon|patna|manchar|vijayawada|hooghly|chandrapur|siliguri|solapur|pimpri|kalyan|pune|puttaparthi|jalna|bhilai|durg|satara|bhopal|jaipur|nandurbar|ratnagiri|barshi|gurgaon|panvel|bhubaneshwar|parbhani|wai|new delhi|kolkata|noida|sinner|navi mumbai|faridabad|bilaspur|lucknow|akola|vadodara|aurangpura|agra|nanded|vishakapatnam|mangalagiri)"
regex = "(" + '|'.join(list(setCities)) + ")"

test_str = ("\"RT @palakzat: VERIFIED: *Empty* Oxygen Cylinder available @ DELHI.\n\n"
	"+91-9313784962\n"
	"Capacity: 22L at ₹35000\n\n"
	"Last verified: 8:38pm on 23 Apr…\"\n"
	"\"RT @ShikhaS46835016: Oxygen Available: \n\n"
	"Contact:9359931390 (Aggrawal Gases )\n\n"
	"Location: Meerut #Verified 1:20\"\n"
	"Patient's condition rapidly deteriorating.  Now need an ICU BED URGENTLY in CHENNAI. Need verified leads. None  of the excel sheets have been of help 😔  @AshwiniDodani pls help https://t.co/Xh228yyd93\n"
	"\"RT @charmjournals: ❗ OXYGEN BEDS AVAILABLE IN PUNE ❗\n\n"
	"NEW LIFE HOSPITAL, KALEWADI\n\n"
	"contact: 9225526566\n\n"
	"verified\n\n"
	"rt to amplify❗\"\n"
	"\"RT @Lakshmimittal12: BHOPAL UPDATE!!\n"
	"💯 Verified\n"
	"All size Oxygen cylinder Refilling is available now. \n"
	"Contact: 89592 28549\n"
	"Singh Sahab!!\n"
	"Go…\"\n"
	"\"RT @leftistcupcake: Oxygen Cylinders for Nagpur. \n"
	"Available, verified at 10:50 pm.\n"
	"98812 00369\n"
	"WhatsApp and call only if urgent! \n"
	"RT to amp…\"\n"
	"\"RT @Roxauraus: ‼Bangalore oxygen cylinders available Mr Ganesh 9686198986 9686196643 Verified at 6 p.m. 23rd April ‼\n"
	"#Bangalore #CovidIndia…\"\n"
	"\"RT @Drugddicted: #Verified #Nagpur \n\n"
	"Oxygen Cylinder available\n\n"
	"Contact: \n"
	"9881200369\n"
	"NOTE: FIRST TRY WHATSAPP \n"
	"🚨CALL IF it's EXTREMELY URGE…\"\n"
	"BEDS VERIFIED PERSONALLY AT 11:09PM https://t.co/XDKxK24NKY\n"
	"\"@Vaisshh_ #Verified #Pune #punecovid #PuneFightsCorona \n"
	"    👉COEP Jumbo Hospital\n\n"
	"👉Nodal officer number020-25502110\n"
	" \n"
	"👉34 bed with oxygen available\"\n"
	"RT @SwatiJulka: #Oxygen gas refill +91 99992 91944 (Taufeeq Gas’s) tomorrow starting 10am at Okhla, pls call him tomorrow. #verified at 11:…\n"
	"Verified: Oxygen in Gurugram https://t.co/cTnyGFFAgO\n"
	"\"RT @dinoswh0r3: Hi All,\n"
	"This is to inform you all that around 1000 oxygen beds will be available at Radha Soami Satsang, Beas Delhi from Su…\"\n"
	"\"RT @TraderMindset: #Lucknow\n\n"
	"#Oxygen Cylinder Refill is happening here since last night\n\n"
	"Verified\n"
	"Plot no 246 kamlabaad barauli Bakshi ka t…\"\n"
	"\"RT @iiiushiii: For people living in #Gorakhpur #Basti\n"
	"#Verified #Oxygen #OxygenCylinders #CovidIndia \n"
	"@MeetUunngLee @abhitksochanahi @sansk…\"\n"
	"\"RT @beingchaisexual: I've got verified leads for Oxygen in SAMBALPUR (ODISHA) \n\n"
	"Dm me for further information. \n\n"
	"Please amplify!\"\n"
	"\"Verified :- 3:38PM , 23 April 2021 \n\n"
	"Hospitals With Vacant Beds In #Delhi \n"
	"Check It Here All Hospitals List . \n\n"
	"#CovidInfo #coronavirus https://t.co/MqmsG1HR0p\"\n"
	"\"RT @Drugddicted: ICU BEDS IN LUCKNOW \n"
	"URGENT 🚨🚨\n\n"
	"reply with latest verified leads.\"\n"
	"\"RT @saahilmenghani: #Verified\n\n"
	"Inox Oxygen tanker arrives at South Delhi's Max hospital. Night sorted here.\n\n"
	"Atleast 700 patients here &amp; at…\"\n"
	"\"RT @saahilmenghani: #Verified\n\n"
	"👉OXYGEN CRISIS at Delhi's 2 hospitals with 181 patients\n\n"
	"👉Oxygen over at Saroj Hospitals in Rohini Sector 14…\"\n"
	"RT @Soumyajit2029: Normal Beds for children (under 18 only) and pregnant women. - Madhukar Rainbow Children's Hospital - Malviya Nagar Metr…\n"
	"\"RT @awwwnchal: GHATKOPAR MUMBAI #verified\n\n"
	"NEW PRICE FOR OXYGEN CYLINDER.\n\n"
	"1 cubic 5 ltr - 12000 rs /-\n"
	"1.5 cubic 10 ltr - 18000/-\n"
	"7 cubic -…\"\n"
	"\"RT @anonyy_mouse: DELHI- Oxygen Cylinder\n"
	"(It will be available tomorrow, 24 April after lunch)\n"
	"Darpan Bhatia\n"
	"Contact no. - 9167103545\n"
	"289,…\"\n"
	"\"VERIFIED: 10L oxygen cylinder @ MUMBAI\n\n"
	"from 10 am tomorrow (24th April)\n"
	"Contact: 7498151214\n"
	"Bhandup,Mumbai\n\n"
	"Last verified: 10:15 pm on 23 April\n\n"
	"#Oxygen #Mumbai\"\n"
	"\"@riddlebrow resposting pls check and confirm @Keshu__10: Beds Available :(Oxygen /General)\n\n"
	"Location:Mumbai ,Brahmand Hospital ,Thane\n\n"
	"Whatsapp Patient Details: 9167105009\n\n"
	"#Verified  12:55\"\n"
	".@MoHFW_India issues the latest Clinical Guidance for the Management of Adult COVID-19 patients with Mild, Moderate, and Severe conditions. Take a look! #IndiaFightsCorona https://t.co/o4xUurBA7a\n"
	"\"#Oxygen \n\n"
	"Indore: Rajesh- 9826500599  Free refill available till 10kg. Verified at 8.00 PM on 23.04.2021\"\n"
	"\"#Indore \n"
	"Oxygen refill, verified !! https://t.co/CA6UGz1QsS\"\n"
	"\"#Verified 8PM. \n\n"
	"Current Oxygen Concentrator stock over, working towards getting new stock. Will update by morning.\n\n"
	"Location: Indore\n\n"
	"#COVIDEmergency2021 #CovidHelp https://t.co/MR2HoshNdA\"\n"
	"\"@sharmapavan919 @SonuSood @DrKumarVishwas @KailashOnline @RahulKothariBJP @BHARGAVABHISHEK @gauravranadive Finally Friend Got bed In Index Hospital Indore 10 minutes ago \n"
	"please contact them they might have few beds available \n"
	"number : 07314044715\n"
	"#Indore #IndoreFightsCorona \n"
	"#Verified ICU bed not able to just checked V care hospital\"\n"
	"\"Finally Friend Got bed In Index Hospital Indore 10 minutes ago \n"
	"please contact them they might have few beds available \n"
	"number : 07314044715\n"
	"#Indore #IndoreFightsCorona \n"
	"#Verified\"\n"
	"There were few crucial weeks in Feb and March when cases were just starting to rise. Let’s zoom in on these four weeks and see how the early signals were missed, valuable time was lost and Indians were led to believe that they were immune to COVID. Thread 1/n https://t.co/9UeDAX1OoH\n"
	"\"So has it ever happened that you ordered food from Zomato, and when the delivery partner comes home and calls you, your phone's caller id says \"\"Zomato Valet\"\" even though you never saved their number on your phone previously ? \n\n"
	"(P.S. The in-built caller id, not Trucaller etc)\"")

matches = re.finditer(regex, test_str, re.MULTILINE | re.IGNORECASE)

for matchNum, match in enumerate(matches, start=1):
    
    print ("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum = matchNum, start = match.start(), end = match.end(), match = match.group()))
    
    for groupNum in range(0, len(match.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = match.start(groupNum), end = match.end(groupNum), group = match.group(groupNum)))

# Note: for Python 2.7 compatibility, use ur"" to prefix the regex and u"" to prefix the test string and substitution.